config/routes.rb
Rails.application.routes.draw do
  root 'check_texts#show'
  post 'check_texts/check_text'
  get 'check_texts/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_texts_controller.rb
class CheckTextsController < ApplicationController
  def check_text
    @spell_check_error = CheckText.check_text(params[:text])
    render action: :show
  end
end
  def show 
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_texts_helper.rb
module CheckTextsHelper
end

app/views/check_texts/show.html.erb
<%= form_with url: check_texts_check_text_path do |form| %>
    <div>
        <%= form.label 'Введите текст:', {:class => 'form-check-label'} %><br>
        <%= form.text_area :text, {:class => 'form-control'}%><br>
    </div>
    <div>
        <%= form.submit 'Проверить', {:class => 'btn btn-lg btn-primary col-md-12'}%> 
    </div><br>
    <div>
        <h2>Результат проверки:</h2>
        <%if !@spell_check_error.nil?%>
        <%@spell_check_error.each do |check_result|%>
            <ul class="list-group">
                <li class="list-group-item">Ошибка в слове: <%=check_result['word']%>, вероятно вы имели ввиду: <%=check_result['s']%></li>
            </ul>
        <%end%>
          <%end%>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Speller</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>